### ISSUE TITLE
Compile Error.........

### ISSUE THREAD

**Issue by rtgtgth** [APT64/KernelAVKiller#2]

**Comment by APT64** [comment]
> _No description provided._

**Comment by APT64** [comment]
attach logs

**Comment by APT64** [comment]
I can't help without looking at the build logs

**Comment by rtgtgth** [comment]
Brother, thank you for replying me, this is the problem I encountered, please trouble you
![1111111111111111111111111](https://github.com/APT64/KernelAVKiller/assets/75723791/03f9c69b-3eb9-4676-b770-acb2a9382988)

**Comment by APT64** [comment]
Oh, you need to install the [WDK](https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk) (Windows Driver Kit) and redirect the solution to the new version.
