### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by zagreoui** [APT64/KernelAVKiller#4]
Hello, I used visual studio2019 to compile the project. After successful compilation, I first installed the configuration in the inf file, and then ran manger.exe. The computer showed that the software could not run. My computer is win10. How can I run the software? Are there any computer system restrictions? Or I made an error in one of the steps. How can I solve the error? Thanks in advance.

**Comment by APT64** [comment]
Hi. Most likely the launch was blocked by some antivirus.

**Comment by zagreoui** [comment]
After I turned off the anti-virus software and ran it again, the result was still the same. It was not a problem with the anti-virus software.
![image](https://github.com/APT64/KernelAVKiller/assets/145044077/ee667f32-69d0-4a71-8f0a-e7f58d7d5105)
